#!/bin/bash

set -a

if [ -f "`pwd`/rancher/vars/main" ]; then
    vars_dir="`pwd`/rancher/vars"
else
    echo "rancher dir not found"
    exit 1
fi

source "${vars_dir}/ports"
source "${vars_dir}/vars"

set +a