version: '2'
services:
  consul:
    image: progrium/consul
    hostname: consul
    command:
      - -server
      - -bootstrap
      - -ui-dir
      - /ui
    labels:
      SERVICE_8302_IGNORE: 'true'
      SERVICE_8500_IGNORE: 'true'
      SERVICE_8301_IGNORE: 'true'
      SERVICE_8300_IGNORE: 'true'
      SERVICE_53_IGNORE: 'true'
      SERVICE_8400_IGNORE: 'true'
      io.rancher.container.pull_image: always
    ports:
      - $port_consul:8500/tcp
    environment:
      LOGSPOUT: ignore