version: '2'
services:
  consul:
    image: consul:0.8.3
    hostname: consul
    environment:
      LOGSPOUT: ignore
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
    ports:
    - 11000:8500/tcp
    command:
    - consul
    - agent
    - -server
    - -bootstrap
    - -data-dir=/consul/data
    - -client=0.0.0.0
    - -ui
    labels:
      SERVICE_8302_IGNORE: 'true'
      SERVICE_8500_IGNORE: 'true'
      SERVICE_8301_IGNORE: 'true'
      SERVICE_8300_IGNORE: 'true'
      SERVICE_53_IGNORE: 'true'
      SERVICE_8400_IGNORE: 'true'
      io.rancher.container.pull_image: always