version: '2'
services:
  docker:
    image: registry:2
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    ports:
      - $port_registry_docker:5000/tcp
    labels:
      io.rancher.container.pull_image: always
    volumes:
      - /opt/rancher_data/registry:/var/lib/registry